# Generated by Django 3.2.9 on 2021-11-23 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tp_book', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='image',
            field=models.ImageField(blank=True, default='', null=True, upload_to='store_im/'),
        ),
    ]
