# Generated by Django 3.2.9 on 2021-11-25 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tp_book', '0003_alter_book_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='slug',
            field=models.CharField(default=None, max_length=150),
            preserve_default=False,
        ),
    ]
