# Generated by Django 3.2.9 on 2021-11-25 08:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tp_book', '0005_alter_book_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='slug',
        ),
    ]
