# Generated by Django 3.2.9 on 2021-11-25 08:45

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('tp_book', '0006_remove_book_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='ro',
            field=models.CharField(default=django.utils.timezone.now, max_length=150),
            preserve_default=False,
        ),
    ]
