# Generated by Django 3.2.9 on 2021-11-25 08:46

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('tp_book', '0007_book_ro'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='ro',
        ),
        migrations.AddField(
            model_name='book',
            name='slug',
            field=models.SlugField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
